apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame-deployment
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: mydocker3692/boardgame:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1                # Kubernetes API version
kind: Service                 # Resource type
metadata:                     # Metadata for the Service
  name: boardgame-ssvc
spec:
  selector:                   # Match pods with label app=boardgame
    app: boardgame
  ports:
    - protocol: TCP           # Protocol used
      port: 80                # Service port exposed
      targetPort: 8080        # Container port to forward traffic to
      nodePort: 30010         # Optional: must be in 30000–32767 range
  type: NodePort              # Service type (case-sensitive!)

