apiVersion: v1                # Kubernetes API version
kind: Service                 # Resource type
metadata:                     # Metadata for the Service
  name: boardgame-ssvc
spec:
  selector:                   # Match pods with label app=boardgame
    app: boardgame
  ports:
    - protocol: TCP           # Protocol used
      port: 80                # Service port exposed
      targetPort: 8080        # Container port to forward traffic to
      nodePort: 30012         # Optional: must be in 30000–32767 range
  type: NodePort              # Service type (case-sensitive!)
